### ISSUE TITLE
Message Short Name / Long Name instead of ID

### ISSUE THREAD

**Issue by defconomicron** [0dayInc/meshtastic#68]
Is there a way to send a message using a short name or long name?

I do see a "from" parameter in the send_text method, however it looks like this will only send a message under a numerical ID.

**Comment by ninp0** [comment]
Can you provide a snippet of code to demonstrate what you're attempting to achieve?  If you're attempting to use the `Meshtastic::MQTT.send_text` method, you'll need to pass in an mqtt subscription object to the `mqtt_obj` parameter to `send_text` which is an object returned by `Meshtastic::MQTT.connect`.  Once connected, `Meshtastic::MQTT.subscribe` is the next step in the flow.  From there you should be able to arbitrarily pass whatever you want in the `from` parameter of `Meshtastic::MQTT.send_text`.  For more detailed usage, checkout `Meshtastic::MQTT.help`.  Hope that helps.

**Comment by ninp0** [comment]
Closing this out, assuming the information provided in the last response was adequate.

**Comment by ninp0** [comment]
@defconomicron you can now send a message using a long name instead of just a numerical id.  See README.md for more info.  Apologies for any confusion.
